name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sub Workflow
        run: |
          echo "Triggering Sub Workflow..."
          gh workflow run sample2.yml --ref main --inputs user_input='${{ github.event.inputs.user_input }}'
