name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Sub Workflow
        uses: ./.github/workflows/sub_workflow.yml
        with:
          data: ${{ github.event.inputs.user_input }}

