name: Sub Workflow

on:
  workflow_call:
    inputs:
      data:
        required: true

jobs:
  sub_job:
    runs-on: ubuntu-latest

    steps:
      - name: Process Data
        run: echo "Processing data: ${{ github.event.workflow_call.inputs.data }}"
