name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true


jobs:
  main_job:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      - name: Call Sub Workflow
        uses: ./.github/workflows/sample2.yml
        with:
          data: ${{ github.event.inputs.user_input }}