name: Sub Workflow

on:
  workflow_call:
    inputs:
      data:
        required: true

jobs:
  sub_job:
    runs-on: ubuntu-latest

    steps:

      - name: User
        uses: actions/checkout@v3


      - name: ip_addr
        run:echo "Processing data: ${{ github.event.workflow_call.inputs.data }}"